### ISSUE TITLE
How to import configuration

### ISSUE THREAD

**Issue by trecloux** [blackbeardapp/docker-machine-export#4]
Thanks for this tool !

I have a question : how can I import the configuration to an other machine ?

**Comment by Pierre-Gilles** [comment]
+1

**Comment by paolomainardi** [comment]
What's the point to write just how to export ?

**Comment by paolomainardi** [comment]
@trecloux ping

**Comment by trecloux** [comment]
As far as I understood, this tool helps exporting a machine to a JSON file.
My question is how can I use this JSON file to import these settings to an other computer ?

**Comment by paolomainardi** [comment]
@trecloux me too
@jambroo please help us!

**Comment by kevinsimper** [comment]
Hi everybody :smile: 

when me and @jambroo made this cli, we needed it to export the certificates into a database, so it was not intended to import at another machine.

There is actually an easy way to export and import a machine. 

You go into the folders with all the machines

```
$ open ~/.docker/machine/machines/
```

and then just zip the folder, ships it to the machine you want it on and then unzip in the same place on that machine :+1:
